image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install && npm run build
    command: npm run start

vscode:
  extensions:
    - ms-dotnettools.csharp@1.23.8:iO8KaJulQm9UBFXlmZNiog==
    - ionide.ionide-fsharp@4.17.0:mFp/s25UhjsPtma7ipgAFg==